name: Debug

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup CPP
      uses: aminya/setup-cpp@v1
      with:
        architecture: ${{ matrix.arch }}
        cmake: true
        ninja: true
    - name: Configure
      run: cmake -GNinja -DCMAKE_BUILD_TYPE=Release -Bbuild
    - name: Ninja build
      run: cmake --build build
    - uses: haya14busa/action-cond@v1
      id: get_command
      with:
        cond: ${{ matrix.os == 'windows-latest' }}
        if_true: "ren build/genshin_patcher.exe patcher_windows-latest.exe"
        if_false: "mv build/genshin_patcher build/patcher_${{ matrix.os }}"
    - name: Rename executable
      run: ${{ steps.get_command.outputs.value }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: DEBUG_${{ matrix.os }}
        path: build/patcher*
