name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup CPP
      uses: aminya/setup-cpp@v1
      with:
        architecture: ${{ matrix.arch }}
        cmake: true
        ninja: true
    - name: Configure
      run: cmake -GNinja -DCMAKE_BUILD_TYPE=Release -Bbuild
    - name: Ninja build
      run: cmake --build build
    - name: [Win] Rename executable
      if: "${{ matrix.os }}" == "Windows"
      run: ren build/genshin_patcher.exe patcher_windows-latest_amd64.exe
    - name: [Unix] Rename executable
      if: "${{ matrix.os }}" != "Windows"
      run: mv build/genshin_patcher build/patcher_${{ matrix.os }}_${{ matrix.arch }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: GHP_${{ matrix.os }}_${{ matrix.arch }}
        path: build/genshin_patcher*
    - name: 2Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/genshin_patcher*"
        allowUpdates: true
